#!/usr/bin/env python3

from random import sample
import hashlib
import sys

# Constants
LETTERS = list('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ')
NUMBERS = list('1234567890')
SPECIALS = list('!@#$%^&*')

## Sample characters from list
def sampleCharacters(chars, count):
    result = ''
    for j in range(0, count):
        result += sample(chars, 1)[0]
    return result

# Default args
doHash = False
length = 16;

# Parse args
argv = sys.argv;
argc = len(argv)

noSpecials = False

for i in range(1, argc):
    arg = argv[i]
    if arg == '-h':
        doHash = True
    elif arg == '-l' and i + 1 < argc and argv[i + 1].isdigit():
        length = int(argv[i + 1])
    elif arg == '-s':
        noSpecials = True

numLetters = int(0.6 * length)
numNumbers = int(0.2 * length)
numSpecials = length - numLetters - numNumbers
if noSpecials:
    numLetters += numSpecials
    numSpecials = 0

passwd = ''
passwd += sampleCharacters(LETTERS, numLetters)
passwd += sampleCharacters(NUMBERS, numNumbers)
passwd += sampleCharacters(SPECIALS, numSpecials)

# scramble
passwd = ''.join(sample(passwd, len(passwd)))
print(passwd)

if doHash:
    print(hashlib.md5(passwd).hexdigest())
